"""Add qualification_type_id to qualification

Revision ID: 8182b5fe5261
Revises: 
Create Date: 2026-03-04 17:16:35.028523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8182b5fe5261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_type_id', sa.Integer(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('qualification_type_id')

    # ### end Alembic commands ###
